# Generated by Django 5.2 on 2025-07-11 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ACAO", "Ação"),
                            ("FII", "Fundo Imobiliário"),
                            ("BDR", "BDR"),
                            ("ETF", "ETF"),
                        ],
                        default="ACAO",
                        max_length=4,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assets_asset",
                "ordering": ["code"],
                "unique_together": {("code", "user")},
            },
        ),
    ]
