# Generated by Django 5.2 on 2025-07-12 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["code"], "verbose_name": "Ativo"},
        ),
    ]
