# Generated by Django 5.2 on 2025-07-11 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardInvestiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField(verbose_name="Mês")),
                ("year", models.IntegerField(verbose_name="Ano")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investiments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card De Dividendo Do Mês",
                "ordering": ["-year", "-month"],
                "unique_together": {("month", "year", "user")},
            },
        ),
        migrations.CreateModel(
            name="ItemInvestiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("COMPRA", "Compra"), ("VENDA", "Venda")],
                        default="COMPRA",
                        max_length=6,
                        verbose_name="Tipo De Ordem",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=8, max_digits=18, verbose_name="Quantidade"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Unitário"
                    ),
                ),
                ("operation_date", models.DateField(verbose_name="Data Da Operação")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.asset"
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="investiments.cardinvestiment",
                    ),
                ),
            ],
        ),
    ]
