# Generated by Django 5.2 on 2025-07-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investiments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iteminvestiment",
            name="order_type",
            field=models.CharField(
                choices=[("BUY", "Buy"), ("SELL", "Sell")],
                default="BUY",
                max_length=6,
                verbose_name="Tipo De Ordem",
            ),
        ),
    ]
