# Generated by Django 5.2 on 2025-07-12 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_alter_asset_options"),
        ("investiments", "0002_alter_iteminvestiment_order_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cardinvestiment",
            options={
                "ordering": ["-year", "-month"],
                "verbose_name": "Card De Investimento Do Mês",
            },
        ),
        migrations.AlterModelOptions(
            name="iteminvestiment",
            options={"verbose_name": "Item De Investimento Do Mês"},
        ),
        migrations.AlterField(
            model_name="iteminvestiment",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assets.asset",
                verbose_name="Ativo",
            ),
        ),
        migrations.AlterField(
            model_name="iteminvestiment",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="investiments.cardinvestiment",
                verbose_name="Card do Mês",
            ),
        ),
        migrations.AlterField(
            model_name="iteminvestiment",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, max_digits=18, verbose_name="Quantidade"
            ),
        ),
    ]
