# Generated by Django 5.2 on 2025-07-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="payment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Pagamento"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="due_date",
            field=models.DateField(verbose_name="Data de Vencimento / Referência"),
        ),
    ]
