# Generated by Django 5.2 on 2025-08-06 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_expense_payment_date_alter_expense_due_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallmentExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome da Compra"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "installments_quantity",
                    models.PositiveIntegerField(verbose_name="Quantidade de Parcelas"),
                ),
                (
                    "first_due_date",
                    models.DateField(verbose_name="Data Da Primeira Parcela"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installment_expenses",
                        to="expenses.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa Parcelada",
                "verbose_name_plural": "Despesas Parceladas",
                "ordering": ["-first_due_date"],
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="installment_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installments",
                to="expenses.installmentexpense",
            ),
        ),
    ]
