# Generated by Django 5.2 on 2025-08-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_installmentexpense_expense_installment_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="expenses.category",
                verbose_name="categoria",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="due_date",
            field=models.DateField(verbose_name="Data de Vencimento"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="installment_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installments",
                to="expenses.installmentexpense",
                verbose_name="parcelado",
            ),
        ),
        migrations.AlterField(
            model_name="installmentexpense",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installment_expenses",
                to="expenses.category",
                verbose_name="categoria",
            ),
        ),
    ]
