# Generated by Django 5.2 on 2025-08-18 15:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_alter_expense_category_alter_expense_due_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome Da Despesa"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor da Despesa"
                    ),
                ),
                (
                    "due_day",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Dia Do Vencimento",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data De Inicio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Término"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_expenses",
                        to="expenses.category",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa Recorrente",
                "verbose_name_plural": "Despesas Recorrentes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaidRecurringExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Data do Pagamento")),
                (
                    "month",
                    models.PositiveIntegerField(verbose_name="Mês de Referência"),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Ano de Referência")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recurring_expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_instances",
                        to="expenses.recurringexpense",
                        verbose_name="despesa recorrente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento de Despesa Recorrente",
                "verbose_name_plural": "Pagamentos de Despesas Recorrentes",
                "unique_together": {("recurring_expense", "month", "year")},
            },
        ),
    ]
